# Custom workflow to build .NET Framework DLL
# Does a build, and will run tests in future after I write the tests, and will publish to nuget once I write that bit

name: Build .NET Framework DLL

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      
    - name: Checkout SwordfishCollections
      uses: actions/checkout@v2.1.0

    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1
  
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.0.2
    
    - name: Restore NuGet Packages
      run: nuget restore Swordfish.NET.Collections.sln
      
    - name: Build Debug DLL
      run: msbuild Swordfish.NET.Collections.sln /p:Configuration=Debug

    - name: Build Release DLL
      run: msbuild Swordfish.NET.Collections.sln /p:Configuration=Release
    
    - name: build nuget packages
      run: msbuild Swordfish.NET.Collections.sln -t:pack -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg -p:Platform="Any CPU" -p:Configuration="Release"

    - name: Publish Swordfish V3 Nuget Package
      run: dotnet nuget push **/release/Swordfish.NET.3.*.nupkg --api-key ${{ secrets.nuget_api_key }} --source https://api.nuget.org/v3/index.json

    - name: Publish V3 Nuget Package
      run: dotnet nuget push **/release/Swordfish.NET.CollectionsV3.3.*.nupkg --api-key ${{ secrets.nuget_api_key }} --source https://api.nuget.org/v3/index.json

    - name: Publish V2 Nuget Package
      run: dotnet nuget push **/release/Swordfish.NET.Collections.2.*.nupkg --api-key ${{ secrets.nuget_api_key }} --source https://api.nuget.org/v3/index.json
